language: python

python:
  - "2.7"
  - "3.5"
  
os:
  - linux
  # - osx # Travis does not support Python in OS X

# command to install dependencies
install: 
  - pip install -q -U pip setuptools nose coveralls matplotlib
  - pip install --upgrade pip setuptools wheel
  - pip install --only-binary=numpy,scipy numpy scipy

# command to run tests
script: 
  - nosetests --with-coverage --cover-package=mozart

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - coveralls